spring:
  application:
    name: ecommerce

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    jpa:
      repositories:
        enabled: true
    elasticsearch:
      repositories:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: utku123



  main:
    allow-bean-definition-overriding: true


security:
  jwt:
    secret-key: cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    access_token_expiration-time: 3600000
    refresh_token_expiration-time: 36000000

